# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphic.ui'
#
# Created: Mon Jun 27 10:54:22 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_IRC(object):
    def setupUi(self, IRC):
        IRC.setObjectName("IRC")
        IRC.resize(695, 695)
        self.layoutWidget = QtGui.QWidget(IRC)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 94, 696, 601))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line = QtGui.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cbDebugSwitch = QtGui.QCheckBox(self.layoutWidget)
        self.cbDebugSwitch.setObjectName("cbDebugSwitch")
        self.horizontalLayout_3.addWidget(self.cbDebugSwitch)
        self.line_6 = QtGui.QFrame(self.layoutWidget)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_3.addWidget(self.line_6)
        self.cbProxySwitch = QtGui.QCheckBox(self.layoutWidget)
        self.cbProxySwitch.setObjectName("cbProxySwitch")
        self.horizontalLayout_3.addWidget(self.cbProxySwitch)
        self.line_4 = QtGui.QFrame(self.layoutWidget)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_3.addWidget(self.line_4)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.sBTryConnectNum = QtGui.QSpinBox(self.layoutWidget)
        self.sBTryConnectNum.setMinimum(1)
        self.sBTryConnectNum.setMaximum(5)
        self.sBTryConnectNum.setProperty("value", 1)
        self.sBTryConnectNum.setObjectName("sBTryConnectNum")
        self.horizontalLayout_3.addWidget(self.sBTryConnectNum)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.sBConnTimeOut = QtGui.QSpinBox(self.layoutWidget)
        self.sBConnTimeOut.setMinimum(1)
        self.sBConnTimeOut.setMaximum(32)
        self.sBConnTimeOut.setProperty("value", 5)
        self.sBConnTimeOut.setObjectName("sBConnTimeOut")
        self.horizontalLayout_4.addWidget(self.sBConnTimeOut)
        self.line_5 = QtGui.QFrame(self.layoutWidget)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_4.addWidget(self.line_5)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.sBThreadNums = QtGui.QSpinBox(self.layoutWidget)
        self.sBThreadNums.setMinimum(1)
        self.sBThreadNums.setMaximum(34)
        self.sBThreadNums.setProperty("value", 32)
        self.sBThreadNums.setObjectName("sBThreadNums")
        self.horizontalLayout_4.addWidget(self.sBThreadNums)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.line_2 = QtGui.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.cmbSockType = QtGui.QComboBox(self.layoutWidget)
        self.cmbSockType.setToolTip("")
        self.cmbSockType.setObjectName("cmbSockType")
        self.cmbSockType.addItem("")
        self.cmbSockType.addItem("")
        self.cmbSockType.addItem("")
        self.horizontalLayout_5.addWidget(self.cmbSockType)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.editIPAddr = QtGui.QLineEdit(self.layoutWidget)
        self.editIPAddr.setObjectName("editIPAddr")
        self.horizontalLayout_5.addWidget(self.editIPAddr)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.editPort = QtGui.QLineEdit(self.layoutWidget)
        self.editPort.setObjectName("editPort")
        self.horizontalLayout_6.addWidget(self.editPort)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.cmbDNS = QtGui.QComboBox(self.layoutWidget)
        self.cmbDNS.setObjectName("cmbDNS")
        self.cmbDNS.addItem("")
        self.cmbDNS.addItem("")
        self.horizontalLayout_7.addWidget(self.cmbDNS)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.editUserName = QtGui.QLineEdit(self.layoutWidget)
        self.editUserName.setObjectName("editUserName")
        self.horizontalLayout_7.addWidget(self.editUserName)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.editUserPwd = QtGui.QLineEdit(self.layoutWidget)
        self.editUserPwd.setObjectName("editUserPwd")
        self.horizontalLayout_9.addWidget(self.editUserPwd)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnStart = QtGui.QCommandLinkButton(self.layoutWidget)
        self.btnStart.setAutoDefault(True)
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout.addWidget(self.btnStart)
        self.btnWait = QtGui.QCommandLinkButton(self.layoutWidget)
        self.btnWait.setObjectName("btnWait")
        self.horizontalLayout.addWidget(self.btnWait)
        self.btnSave = QtGui.QCommandLinkButton(self.layoutWidget)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.btnQuit = QtGui.QCommandLinkButton(self.layoutWidget)
        self.btnQuit.setObjectName("btnQuit")
        self.horizontalLayout.addWidget(self.btnQuit)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.line_3 = QtGui.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.textBrowser = QtGui.QTextBrowser(self.layoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_5.addWidget(self.textBrowser)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.layoutWidget1 = QtGui.QWidget(IRC)
        self.layoutWidget1.setGeometry(QtCore.QRect(3, 3, 691, 109))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.TextIPInput = QtGui.QPlainTextEdit(self.layoutWidget1)
        self.TextIPInput.setMaximumSize(QtCore.QSize(16777215, 367))
        self.TextIPInput.setObjectName("TextIPInput")
        self.verticalLayout_2.addWidget(self.TextIPInput)

        self.retranslateUi(IRC)
        QtCore.QObject.connect(self.btnQuit, QtCore.SIGNAL("clicked()"), IRC.close)
        QtCore.QMetaObject.connectSlotsByName(IRC)

    def retranslateUi(self, IRC):
        IRC.setWindowTitle(QtGui.QApplication.translate("IRC", "IRC扫描 Linux版", None, QtGui.QApplication.UnicodeUTF8))
        self.cbDebugSwitch.setText(QtGui.QApplication.translate("IRC", "显示调试信息", None, QtGui.QApplication.UnicodeUTF8))
        self.cbProxySwitch.setText(QtGui.QApplication.translate("IRC", "使用代理", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("IRC", "连接次数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("IRC", "连接超时时间", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("IRC", "并发线程数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("IRC", "代理类型", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSockType.setItemText(0, QtGui.QApplication.translate("IRC", "SOCK4", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSockType.setItemText(1, QtGui.QApplication.translate("IRC", "SOCK5", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSockType.setItemText(2, QtGui.QApplication.translate("IRC", "HTTP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("IRC", "代理地址", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("IRC", "代理端口", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("IRC", "远程DNS优化", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbDNS.setItemText(0, QtGui.QApplication.translate("IRC", "True", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbDNS.setItemText(1, QtGui.QApplication.translate("IRC", "False", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("IRC", "用户名", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("IRC", "密码", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStart.setText(QtGui.QApplication.translate("IRC", "开始探测", None, QtGui.QApplication.UnicodeUTF8))
        self.btnWait.setText(QtGui.QApplication.translate("IRC", "清空", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave.setText(QtGui.QApplication.translate("IRC", "保存结果", None, QtGui.QApplication.UnicodeUTF8))
        self.btnQuit.setText(QtGui.QApplication.translate("IRC", "退出", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("IRC", "结果打印", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("IRC", "IP地址范围", None, QtGui.QApplication.UnicodeUTF8))

